---
- name: Ensure git and docker-compose is available
  apt:
    name:
    - git
    - docker-compose
    - docker
    state: present

- name: Create user
  user:
    name: mailserver
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: docker
    state: present

- name: Ensure base / data directories for mailserver exist
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: directory
  loop:
    - { path: "/srv/mailserver", owner: "mailserver" }

- name: Ensure docker-compose.yml for mailserver
  template:
    src: docker-compose.j2
    dest: "/srv/mailserver/docker-compose.yml.example"

- name: Ensure mailserver install script
  template:
    src: install.j2
    dest: "/srv/mailserver/install.sh"
    mode: 0777
