---
- name: Ensure git and docker-compose is available
  apt:
    name:
    - git
    - docker-compose
    - docker
    state: present

- name: Create user
  user:
    name: whiteboard
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: docker
    state: present

- name: Ensure base / data directories for whiteboard exist
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: directory
  loop:
    - { path: "/srv/whiteboard", owner: "whiteboard" }      

- name: Ensure docker-compose.yml for whiteboard
  template:
    src: docker-compose.j2
    dest: "/srv/whiteboard/docker-compose.yml"

- name: Ensure environment file
  template:
    src: env.j2
    dest: "/srv/whiteboard/.env"

- name: Ensure rocketchat nginx conf is present
  template:
    src: whiteboard.nginx
    dest: "/etc/nginx/{{ nginx_domain_name }}.d/whiteboard.conf"
    #    notify: reload nginx

