---
- name: Ensure git and docker-compose is available
  apt:
    name:
    - git
    - docker-compose
    - docker
    state: present

- name: Create user
  user:
    name: rocketchat
    shell: /bin/bash
    password: '!'
    update_password: on_create
    groups: docker
    state: present

- name: Ensure base / data directories for rocketchat exist
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    state: directory
  loop:
    - { path: "/srv/rocketchat/data", owner: "rocketchat" }      
    - { path: "/srv/rocketchat/data/db", owner: "999" }
    - { path: "/srv/rocketchat/data/dump", owner: "999" }

- name: Ensure docker-compose.yml for rocketchat
  template:
    src: docker-compose.j2
    dest: "/srv/rocketchat/docker-compose.yml"

- name: Ensure rocketchat nginx conf is present
  template:
    src: rocketchat.nginx
    dest: "/etc/nginx/{{ nginx_domain_name }}.d/rocketchat.conf"
    #    notify: reload nginx

- cron:
    name: "Cronjob restart rocketchat"
    minute: "00"
    hour: "02"
    job: "(cd /srv/rocketchat; /usr/bin/docker-compose down; /usr/bin/docker-compose up -d)&"
    user: root
    state: absent
