---
- name: Start whiteboard
  shell: docker-compose up -d
  args:
    chdir: /srv/whiteboard

- name: Start jitsi
  shell: install.sh
  args:
    chdir: /srv/jitsi

- name: Start cryptpad
  shell: docker-compose up -d
  args:
    chdir: /srv/cryptpad

- name: Start watchtower
  shell: docker-compose up -d
  args:
    chdir: /srv/watchtower
